### ISSUE TITLE
Fixed width for the calculator

### ISSUE THREAD

**Issue by Ja-Uyoma** [Ja-Uyoma/Calculator#2]
The calculator needs a fixed width in order to prevent it growing and shrinking along with changes in the size of the browser window. This would give all users the same experience while using it.

**Comment by Uriyo** [comment]
Try to work around  media query, This would resolve the issue

**Comment by Ja-Uyoma** [comment]
Had the exact same thought. Thank you for the pointers. Really appreciate the help

**Comment by Ja-Uyoma** [comment]
Explicitly setting the width to 500px both restricts the width and prevents the buttons from growing or shrinking depending on the size of their container.
